name: helm-test
on:
  pull_request:
    branches:
      - main
      - release*
    paths:
      - charts/**
      - .github/workflows/helm-test.yaml

permissions: read-all

jobs:
  helm-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6 # v2.3.1
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@b0d4458c71155b54fcf33e11dd465dc923550009 # v2.0.1

      - name: Run chart-testing (lint)
        run: ct lint --target-branch=main --check-version-increment=false
